changelog:
  exclude:
    labels:
      - 'Duplicate'
      - 'Out of Scope'
      - 'Wontfix'
      - 'Good First Issue'
      - 'Help Wanted'
  categories:
    - title: 'Breaking Changes'
      labels:
        - 'Type: Breaking'
    - title: 'Features'
      labels:
        - 'Type: Feature'
        - 'Type: Enhancement'
    - title: 'Bug Fixes'
      labels:
        - 'Type: Bug'
    - title: 'Indexers & Search'
      labels:
        - 'Type: Indexer'
        - 'Area: Indexers'
    - title: 'Downloads & Imports'
      labels:
        - 'Area: Downloads'
    - title: 'Subtitles'
      labels:
        - 'Area: Subtitles'
    - title: 'UI'
      labels:
        - 'Area: UI'
    - title: 'Monitoring & Automation'
      labels:
        - 'Area: Monitoring'
    - title: 'Library'
      labels:
        - 'Area: Library'
    - title: 'Documentation'
      labels:
        - 'Type: Docs'
    - title: 'Dependencies'
      labels:
        - 'Dependencies'
    - title: 'Performance'
      labels:
        - 'Area: Quality'
    - title: 'Maintenance & Refactoring'
      labels:
        - 'Type: Chore'
        - 'Type: Refactor'
    - title: 'Other Changes'
      labels:
        - '*'
